---
title: "r-for-panel-yofun"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(magrittr)
```

```{r}
library(readr)
fatality <- read_csv("https://raw.githubusercontent.com/tpemartin/Econometric-Analysis/master/Part%20II/fatality.csv")
```
```{r}
class(fatality) #從這4個角度看待這資料，data frame本身沒有panel的概念所以要透過pdata.frame做另外的轉換
```

```{r}
fatality %>% summarise_all(funs(class))
```

```{r}
library(plm) #panel linear model
```

```{r}
pdf_fatality<-pdata.frame(fatality,c("state","year")) #c是產生向量 讓電腦知道哪個是i哪個是t
```

```{r}
class(pdf_fatality)
```


```{r}
#用%>%記得先引入dplyr
#各州啤酒稅（beertax）與車禍死亡率（mrall）
library(ggplot2) #在canvas畫布上層疊 + geometric objects +...(都是以geom_開頭)
fatality %>% #原本的data 用%>%先確定DPLYR有引入
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000))) #加上層疊的圖形叫做point，aes是個函數(X軸是甚麼Y軸是甚麼)
#變數經過轉換再畫所以*1000 要記得用I 如果直接用mrall就不用I
#正向關係 所有州來看的 打算用顏色區分不同的州
#aes中stroke指點的外圈顏色，fills指內部顏色，還有colour size group shape等等
```
非mapping的color設定，沒有把color寫在aes函數中
```{r}
fatality %>% 
  ggplot()+
  geom_point(
    aes(x=beertax,y=I(mrall*1000)),
    color="blue")

```

mapping的color設定
```{r}
fatality %>% 
  ggplot()+
  geom_point(
    aes(x=beertax,
        y=I(mrall*1000),
        color=as.factor(state))) #factor是類別 本來沒轉換時會用漸層來畫 #color由指定的資料來map出來的，用年份就用year,gglot會根據資料的type來決定顏色要怎麼上
#同個顏色群很像是負斜率的 每個州有自己的固定效果
```

```{r}
fatality$state%>% class #被當成連續的數值了，不是間斷的概念 所以資料視覺化的時候是用漸層來畫
```

```{r}
fatality %>% 
  ggplot()+
  geom_point(
    aes(x=beertax,
        y=I(mrall*1000),
        color=as.factor(state),
        shape=as.factor(year)))
```

```{r}
fatality %>% 
  group_by(state) %>% #依state分組進行以下程序：不然沒有打groupby的話就會是全部的樣本點平均
  mutate(
    mrall_demean=mrall-mean(mrall), #mean是要依照state來分群計算的，所以前面用group_by
    beertax_demean=beertax-mean(beertax)
    ) %>%
  select(mrall_demean,beertax_demean,state) %>%
  ungroup() -> demean_results # grouping variable會被保留 存在demean_results這dataframe
```

```{r}
demean_results %>%
  ggplot()+ #先叫出畫布
  geom_point(aes(x=beertax_demean,y=mrall_demean,color=as.factor(state)))+
  geom_smooth(aes(x=beertax_demean,y=mrall_demean),method = "lm",se=FALSE)
#geom_smooth畫樣本配適出來的平滑的線 lm指要線性的結果
```

```{r}
lm(mrall_demean~beertax_demean,data=demean_results) #要算那條平滑線的斜率-6.559

```

```{r}
lm(mrall~beertax+factor(state), data=fatality) %>% summary()
```

```{r}
fatality %>% lm(data=., mrall~factor(state)) -> results
# results$residuals 也會是demean的結果
```

```{r}
model<-mrall~beertax
```

##plm

OLS: model="pooling"
```{r}
library(plm)
#fatality<-
  #pdata.frame(fatality,c("state","year"))
model<-mrall~beertax
pool1<-plm(model, data=fatality, model='pooling')
summary(pool1)
```

Random effect: model="random"
```{r}
re1<-plm(model, data=fatality, model='random')
summary(re1)
```


Fixed effect:model="within"
```{r}
fe1<-plm(model, data=fatality, model='within', effect='individual')
summary(fe1)
```

```{r}
fe2<-plm(model, data=fatality, model='within', effect='twoways') #兩個固定效果要寫twoways
summary(fe2)
```

```{r}
library(stargazer)
stargazer(pool1,re1,fe1,fe2,type='text',
          column.labels = c("Pooled OLS","RE","FE-individual","FE-two-ways"))
```

```{r}
phtest(fe1,re1) #p-value很小 reject
#Ho:Vit獨立於beertaxit
```

```{r} 
fatality %>% #加其他控制變數
  plm(mrall~beertax+unrate, data=., method="within",effect = "individual")
```

#資料分析流程
##確認變數class正確性
```{r}
fatality %>%
  mutate(
    state=as.factor(state),
    year=as.ordered(year)
  ) -> fatality #之後就不用每次碰到都要轉換一次
```
#作圖
##資料分析

```{r}
lm(mrall~beertax+state, data=fatality)
```
demean前40州的圖
```{r}
fatality %>%
  filter(state==40) %>%
  ggplot()+
  geom_point(
    aes(
      x=beertax,
      y=I(mrall*1000),
      color=as.factor(state),
      size=5
    )
  )
```
demean後40州的圖
```{r}
demean_results %>%
  filter(state==40) %>%
  ggplot()+
  geom_point(
    aes(
      x=beertax,
      y=I(mrall*1000),
      color=as.factor(state),
      size=5
    )
  )
```